FROM alpine:latest
RUN dd if=/dev/zero bs=1M count=10 of=/zero
RUN rm /zero
CMD true
ENTRYPOINT ["/bin/sh", "-c"]
ENV SOME_ENV=1
EXPOSE 8080/tcp 5353/udp
ONBUILD ADD ./ /somewhere
USER nobody
VOLUME /volume
WORKDIR /home
